### ISSUE TITLE
Request Money is not working

### ISSUE THREAD

**Issue by cizu64** [bchavez/Coinbase#57]
The request money is not working. I tried this:

 

```
> var accounts = await client.Transactions.RequestMoneyAsync(accountId, new RequestMoney
>             {
>                 To = email,
>                 Type = "request",
>                 Amount = amount,
>                 Currency = coinType,
>                 Description = description
>             });
```
```
> var result = coinBase.RequestPayment("myaccountid", "test@gmail.com", 0.01, "BTC",null).Result;
```

It throwing an exception:

> 
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): POST https://api.coinbase.com/v2/accounts/4b0b05c4-e148-53f5-b077-0a101d7d6487/transactions
   at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CoinBasePayment.WalletPay.<RequestPayment>d__3.MoveNext() in C:\Users\CHARLES\Documents\Visual Studio 2015\Projects\StakersClub\CoinBase\WalletPay.cs:line 36
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at CongateClient.Program.Main(String[] args) in C:\Users\CHARLES\Documents\Visual Studio 2015\Projects\Coingate.Net\CongateClient\Program.cs:line 40

**Comment by bchavez** [comment]
Hi Charles,

You'll have to find out why.

To do that:

[1]:https://github.com/bchavez/Coinbase/blob/4e5a0c5a2d0bd962617718893a32c50433e0abc4/Source/Coinbase/CoinbaseClient.cs#L91-L105

* Start Fiddler.
* Call the [`EnableFiddlerDebugProxy`][1] method to setup Fiddler debugging in your `CoinbaseClient`.
* Run the call again and inspect the Fiddler output for the request/response and see why it failed.

**Comment by bchavez** [comment]
Hey Charles,

I think this is a bug in the Coinbase REST API. 

Here's the currently tracked issue: https://github.com/coinbase/coinbase-ios-sdk/issues/54

Thanks,
Brian

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nczfdg/coinbase_support_has_repeatedly_ignored_requests/
