### ISSUE TITLE
'Could not load type 'Flurl.Http.HttpCall' from assembly 'Flurl.Http

### ISSUE THREAD

**Issue by JesperKuipers** [bchavez/Coinbase#73]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |         5.1.2.0        |
| .NET Core?                   |           idk      |
| .NET Full Framework?   |      4.7.2          |
| Windows OS?              |     last stable build             |
| Linux OS?                    |             no     |
| Visual Studio?              |          last stable version        |

### What's the problem?
'Could not load type 'Flurl.Http.HttpCall' from assembly 'Flurl.Http, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null'.'

### What possible solutions have you considered? 
reinstalling framework, debugging to make sure the API key and secret API key is working

### Do you have a sample code to show what you're trying to do?

![image](https://user-images.githubusercontent.com/44586411/104370204-d2443f80-551e-11eb-85e2-ae07a1bdbe20.png)

### What is the HTTP request JSON and response JSON?

![image](https://user-images.githubusercontent.com/44586411/104370597-64e4de80-551f-11eb-9b9e-680c9f89d53d.png)

**Comment by bchavez** [comment]
@JesperKuipers if you downgrade the `Flurl.Http` nuget package to 2.4.2; and clean/rebuild does the issue go away?

I suspect this is because **Coinbase** is built against `Flurl.Http` 2.4.0 and the v3.0+ `Flurl.Http` is incompatible.

**Comment by JesperKuipers** [comment]
I will try that thanks

**Comment by JesperKuipers** [comment]
Still this error: System.TypeLoadException: 'Could not load type 'Flurl.StringExtensions' from assembly 'Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null'.'

But i found that FLurl has the version 3.0.10. so it wanst flurl.http.

Which version do you recommend for the flurl?

**Comment by JesperKuipers** [comment]
Okay 2.8.0.0 works for me but now I get a new error:


Flurl.Http.FlurlHttpException
  HResult=0x80131500
  Message=Call failed. An error occurred while sending the request. GET https://api.coinbase.com/v2/prices/ETH-USD/spot
  Source=Flurl.Http
  StackTrace:
   at Flurl.Http.FlurlRequest.<HandleExceptionAsync>d__23.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__19.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CoinBaseClient.Form1.<Get_spotprice_of_BTCEURO>d__3.MoveNext() in C:\Users\jespe\source\repos\CoinBaseClient\CoinBaseClient\Form1.cs:line 46
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CoinBaseClient.Form1.<button1_Click>d__4.MoveNext() in C:\Users\jespe\source\repos\CoinBaseClient\CoinBaseClient\Form1.cs:line 56

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
HttpRequestException: An error occurred while sending the request.

Inner Exception 2:
WebException: Unable to connect to the remote server

Inner Exception 3:
SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888

**Comment by JesperKuipers** [comment]
Ah i forgot to remove the client.EnableFiddlerDebugProxy("http://localhost.:8888");
My Coinbase is IP locked aswell so ye thats on me. Thank you
